---
- name: Generate Configuration file for Juniper 4550 as PE router and Install it
  hosts:
    - MPLS_PE
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    username: root
    password: MoSline234
    connection_settings:
      host: "{{ ansible_host }}"
      port: 22
      user: "{{ username }}"
      passwd: "{{ password }}"
      timeout: 120
    tmp_dir: "tmp"
    fragments_dir: "fragments"
    templates_dir: "template"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"
  
  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes
      
    - name: confirm or create fragmenst directory
      file:
        path: "{{ fragments_dir }}"
        state: directory
      run_once: yes
        
    - name: Generate fragments of initial configuration file template
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: yes
      with_items: 
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-system.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-system.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-chassis.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-chassis.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-ethernet-switching-options.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-ethernet-switching-options.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-interfaces.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-interfaces.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-policy-options.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-policy-options.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-protocols.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-protocols.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-routing-instances.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-routing-instances.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-routing-options.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-routing-options.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-snmp.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-snmp.set.conf" }
        - {src: '{{ templates_dir }}/Juniper-ex4550-PE-vlans.set.j2',dest: "{{ fragments_dir }}/Juniper-ex4550-PE-vlans.set.conf" }
    
    - assemble: #Asemble initiall configuration file
        src: "{{ fragments_dir }}"
        dest: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"
        
    - name: delete generated configuration file
      file:
        path: '{{ fragments_dir }}'
        state: absent

 
    #- name: install generated configuration file onto device
      #juniper_junos_config:
      #  provider: "{{ connection_settings }}"
      #  src: "{{ conf_file }}"
      #  load: replace
      #  comment: "playbook base-settings.yaml, commit confirmed"
      #  confirmed: 5
      #  diff: yes
      #  dest_dir: "{{ tmp_dir }}"
      #  ignore_warning: "statement not found"   
     # register: config_results
     # notify: confirm previous commit
      
   # - name: show configuration change
   #   debug:
   #     var: config_results.diff_lines
   #   when: config_results.diff_lines is defined

    #- name: delete generated configuration file
      #file:
        #path: "{{ conf_file }}"
        #state: absent
        

  handlers:
    - name: confirm previous commit
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        comment: "playbook base-settings.yaml, confirming previous commit"
        commit: yes
        diff: no
